name: Build

on:
  push:
    tags:
    - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo bash linux-deps.sh
      - name: build
        run: ninja
