name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo bash linux-deps.sh
      - name: build 
        run: ninja
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
            name: Artifacts
            path: build/
            
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: fgOS.iso
