name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: m4
      run: aclocal
    - name: autoconf
      run: autoconf
    - name: automake
      run: automake --add-missing
    - name: autoreconf
      run: autoreconf
    - name: configure
      run: ./configure
    - name: make
      run: make
